server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
#        namespace: 74f2efa5-1e9e-4046-b77d-77b5c8a17356
        #指定 nacos server 的地址  ，地址不要加 http
        server-addr: localhost:8848
        cluster-name: BJ
        metadata:
          version: v1
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          #这里的 destination 要和生产者那里保持一致
          destination: add-bonus-yaya
          # 如果是rockemq 这里一定要设置
          # 如果是其他的 mq 这里可以不用设置 group
          group: binder-group

  application:
    #服务名称尽量用 - ，不要用_ ,更不要用特殊字符
    name: user-center
  zipkin:
    base-url: http://127.0.0.1:9411/
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
#    sender:
#      type: web  # 设置使用http的方式传输数据
  sleuth:
    sampler:
      #抽样率  默认是 0.1，只有10% 的数据上报给zipkin server 以免影响应用性能
      probability: 1.0

# 先注释掉  用 stream
#rocketmq:
#  name-server: 127.0.0.1:9876
  #消费组的名称不在这里写



logging:
  level:
    com.alibaba.nacos: error
    org.springframework.cloud.sleuth: debug

#jwt 加密配置 若默认配置不符合需求 可以在配置文件中进行自定义
jwt:
  # 秘钥
  secret: 5d1IB9SiWd5tjBx&EMi^031CtigL!6jJ
  # jwt有效期，单位秒
  expire-time-in-second: 1209600



