server:
  port: 8010
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 指定命名空间
#        namespace: 74f2efa5-1e9e-4046-b77d-77b5c8a17356
        # 指定集群名称
        cluster-name: BJ
        #元数据  控制微服务的版本
        metadata:
          version: v1
          target-version: v1
  application:
    name: content-center

#属性配置的方式配置ribbon 负载均衡的规则 ,局部配置Rule；ribbon 不支持配置文件全局配置的
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#ribbon 开启饥饿加载，为user-center微服务
ribbon:
  eager-load:
    enabled: true
    clients: user-center


#feign 的自定义日志级别 这一段是 springboot 的日志级别定义方式，feign有自己自定义日志的级别，但是这一段不能少
logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug

#配置文件配置feign的日志级别- 局部配置
feign:
  client:
    config:
      #微服务名称
      # 如果改为全局配置的话，把 user-center改为 default
      user-center:
        loggerLevel: full
  # feign原来是用 httpUrlConnection 连接的，但是这种方式没有连接池，所以启用 有连接池的 apache 的 httpclient 或者 okhttp 来请求
  # 让feign启用okhttp作为发送http请求的客户端
  okhttp:
    enabled: true
  httpclient:
    # 让feign启用httpclient作为发送http请求的客户端
#    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign 单个路径的最大连接数
    max-connections-per-route: 50
